Implemented db_lint script to check for missing devices. Added Z:SLWXSPILL device.

diff --git a/db/Makefile b/db/Makefile
--- a/db/Makefile
+++ b/db/Makefile
@@ -3,15 +3,36 @@ help:
 	@echo "make help		=> Display description of targets"
 	@echo "make clean		=> Remove temporary and .lis files"
 	@echo "make db_diff		=> Calculate a diff between .dabbel files and what's in the device database"
+	@echo "make db_lint             => Check that all devices assigned to Mu2eER nodes are represented in .dabbel files"
 	@echo "make db_sync		=> Synchronize .dabbel files with what's in the device database"
 	@echo "                      	   !! WARNING !! this will over-write your .dabbel files"
-	@echo "make db_test_check 	=> Run devices_test.dabbel in syntax-checking mode"
 	@echo "make db_test		=> Submit devices_test.dabbel to DABBEL"
+	@echo "make db_test_check 	=> Run devices_test.dabbel in syntax-checking mode"
 
 # Remove temporary and listing files
 clean:
 	@echo "-m-> Cleaning... "
 	@-rm dbtemp *.lis
+
+# Ensure that every device assigned to the test/production node appears in a database script
+db_lint: db_test_check
+	@echo "-m-> Checking that all SRSD devices appear in devices_test.dabbel..."
+	@acl "list node=srsd '%nm'" | awk '{if(NR>5)print}' >dbtemp
+	@dev_missing=0; \
+	input="dbtemp"; \
+	while IFS= read -r line; \
+	do \
+		if ! grep -q "MOD $$line " devices_test.dabbel; then \
+			echo "$$line was not found in devices_test.dabbel"; \
+			((dev_missing=dev_missing+1)); \
+		fi \
+	done < "$$input"; \
+	if [ "$$dev_missing" -gt 0 ]; then \
+		echo "$$dev_missing device(s) not found."; \
+		exit 1; \
+	fi
+	@rm dbtemp
+	@echo "-m-> Done, all devices found."
 
 # Show a diff between the device database files and what is in the database right now
 db_diff:
